// SPDX-License-Identifier: MIT

use crate::support::*;
use bindport_registry::{OutputFileRecord, OutputFileScope, OutputFileStatus};

fn output_scope_for_root(root: &Path) -> OutputFileScope {
    OutputFileScope::new(
        root.join(".bindport/generated"),
        root.to_path_buf(),
        None,
        None,
    )
}

#[test]
fn render_command_writes_config_files_and_records_ownership() {
    let registry_path = temp_registry_path("render-output-registry");
    let root = temp_test_dir("render-output-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-project\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"render.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let rendered_path = root
        .join(".bindport")
        .join("generated")
        .join("traefik")
        .join("web.yml");
    let dry_run = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik", "--dry-run"])
        .output()
        .expect("dry-run render");

    assert!(
        dry_run.status.success(),
        "render dry-run failed: {}",
        String::from_utf8_lossy(&dry_run.stderr)
    );
    let dry_run_stdout = String::from_utf8(dry_run.stdout).expect("dry-run stdout");
    assert!(dry_run_stdout.contains("would render traefik: 1 files"));
    assert!(dry_run_stdout.contains("traefik/web.yml"));
    assert!(!rendered_path.exists());

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");

    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    assert!(
        String::from_utf8(render.stdout)
            .expect("render stdout")
            .contains("rendered traefik: 1 files")
    );

    let contents = fs::read_to_string(&rendered_path).expect("rendered file");
    assert!(contents.contains("Generated by BindPort"));
    assert!(contents.contains("is stopped"));

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    assert!(
        status_output.status.success(),
        "status failed: {}",
        String::from_utf8_lossy(&status_output.stderr)
    );
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");
    let rendered_path_string = rendered_path
        .canonicalize()
        .expect("canonical rendered path")
        .display()
        .to_string();

    assert_eq!(status["schema_version"], "0.4");
    assert_eq!(status["outputs"][0]["name"], "traefik");
    assert_eq!(status["outputs"][0]["pending"], 0);
    assert_eq!(status["outputs"][0]["rendered"], 1);
    assert_eq!(status["outputs"][0]["removed"], 0);
    assert_eq!(status["outputs"][0]["error"], 0);
    assert_eq!(status["services"][0]["outputs"][0]["name"], "traefik");
    assert_eq!(status["services"][0]["outputs"][0]["status"], "rendered");
    assert_eq!(
        status["services"][0]["outputs"][0]["path"],
        rendered_path_string
    );
    assert_eq!(status["services"][0]["proxy"]["adapter"], "traefik");
    assert_eq!(status["services"][0]["proxy"]["rendered"], true);
    assert_eq!(
        status["services"][0]["proxy"]["target"],
        rendered_path_string
    );

    let rerender = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("rerender output");

    assert!(
        rerender.status.success(),
        "rerender failed: {}",
        String::from_utf8_lossy(&rerender.stderr)
    );
}

#[test]
fn render_scopes_same_output_and_route_to_distinct_output_roots() {
    let registry_path = temp_registry_path("render-scoped-roots-registry");
    let first_root = temp_test_dir("render-scoped-roots-first");
    let second_root = temp_test_dir("render-scoped-roots-second");
    let port = free_loopback_port();
    let config = format!(
        "project = \"render-scoped-roots\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"scoped.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
    );

    fs::write(first_root.join(".bindport.toml"), &config).expect("write first config");
    fs::write(second_root.join(".bindport.toml"), &config).expect("write second config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&first_root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");
    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    for root in [&first_root, &second_root] {
        let render = bindport_with_registry(&registry_path)
            .current_dir(root)
            .args(["render", "traefik"])
            .output()
            .expect("render output");
        assert!(
            render.status.success(),
            "render failed in {}: {}",
            root.display(),
            String::from_utf8_lossy(&render.stderr)
        );
        assert!(root.join(".bindport/generated/traefik/web.yml").is_file());
    }

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    assert!(
        status_output.status.success(),
        "status failed: {}",
        String::from_utf8_lossy(&status_output.stderr)
    );
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");

    assert_eq!(status["outputs"][0]["name"], "traefik");
    assert_eq!(status["outputs"][0]["rendered"], 2);
}

#[test]
fn render_all_writes_every_enabled_output() {
    let registry_path = temp_registry_path("render-all-registry");
    let root = temp_test_dir("render-all-root");
    let template_dir = root.join(".bindport").join("templates");
    fs::create_dir_all(&template_dir).expect("template dir");
    fs::write(
        template_dir.join("debug-route.txt.j2"),
        "debug {{ output.name }} {{ route.service }} {{ vars.mode }} {{ route.target_url }}\n",
    )
    .expect("write debug template");

    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-all\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"render-all.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n[[outputs]]\nname = \"debug\"\ntemplate = \"debug-route\"\nroot = \".bindport/generated\"\ntarget = \"debug/{{{{ route.service }}}}.txt\"\nauto_render = false\n[outputs.vars]\nmode = \"dev\"\n"
        ),
    )
    .expect("write render config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "--all"])
        .output()
        .expect("render all outputs");

    assert!(
        render.status.success(),
        "render all failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    let stdout = String::from_utf8(render.stdout).expect("render stdout");
    assert!(stdout.contains("rendered traefik: 1 files"));
    assert!(stdout.contains("rendered debug: 1 files"));

    assert!(root.join(".bindport/generated/traefik/web.yml").is_file());
    assert_eq!(
        fs::read_to_string(root.join(".bindport/generated/debug/web.txt"))
            .expect("debug rendered file"),
        format!("debug debug web dev http://127.0.0.1:{port}")
    );
}
#[test]
fn render_env_local_output_writes_opt_in_dotenv_file() {
    let registry_path = temp_registry_path("render-env-local-registry");
    let root = temp_test_dir("render-env-local-root");
    fs::write(
        root.join(".bindport.toml"),
        "project = \"env-local-project\"\ndefault_range = \"29430-29439\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"env-local.localhost\"\n[[outputs]]\nname = \"env-local\"\ntemplate = \"bindport-env-local\"\ntarget = \"apps/{{ route.service }}/.env.local\"\nauto_render = false\n",
    )
    .expect("write env-local config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "env-local"])
        .output()
        .expect("render env-local output");

    assert!(
        render.status.success(),
        "render env-local failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    let stdout = String::from_utf8(render.stdout).expect("render stdout");
    assert!(stdout.contains("rendered env-local: 1 files"));

    let env_file = root.join("apps/web/.env.local");
    let contents = fs::read_to_string(&env_file).expect("env-local file");
    let rendered_port = dotenv_value(&contents, "PORT")
        .expect("rendered port")
        .parse::<u16>()
        .expect("rendered port is numeric");
    assert!((29430..=29439).contains(&rendered_port));
    assert!(contents.contains(r#"BINDPORT_PROJECT="env-local-project""#));
    assert!(contents.contains(r#"BINDPORT_SERVICE="web""#));
    assert!(contents.contains(r#"BINDPORT_STATE="stopped""#));
    assert!(contents.contains(&format!(
        r#"BINDPORT_TARGET_URL="http://127.0.0.1:{rendered_port}""#
    )));
    assert!(contents.contains(r#"BINDPORT_HOSTNAME="env-local.localhost""#));
    assert!(contents.contains(r#"BINDPORT_ROUTE_URL="http://env-local.localhost""#));
}
#[test]
fn render_repair_records_externally_modified_owned_files() {
    let registry_path = temp_registry_path("render-repair-modified-registry");
    let root = temp_test_dir("render-repair-modified-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-repair\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"repair.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");
    let rendered_path = root.join(".bindport/generated/traefik/web.yml");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");
    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");
    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    fs::write(&rendered_path, "external change").expect("modify rendered file");

    let repair = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "--repair", "traefik"])
        .output()
        .expect("repair output");
    assert!(
        repair.status.success(),
        "repair failed: {}",
        String::from_utf8_lossy(&repair.stderr)
    );
    let repair_stdout = String::from_utf8(repair.stdout).expect("repair stdout");
    assert!(repair_stdout.contains("repaired traefik: 0 files"));
    assert!(repair_stdout.contains("preserved traefik: 1 externally modified files"));
    assert_eq!(
        fs::read_to_string(&rendered_path).expect("preserved file"),
        "external change"
    );

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");

    assert_eq!(status["outputs"][0]["rendered"], 0);
    assert_eq!(status["outputs"][0]["error"], 1);
    assert_eq!(status["services"][0]["outputs"][0]["status"], "error");
    assert_eq!(
        status["services"][0]["outputs"][0]["reason"],
        "external_modified"
    );
}

#[test]
fn render_ignores_foreign_scoped_output_rows_without_blocking() {
    let registry_path = temp_registry_path("render-stale-foreign-registry");
    let root = temp_test_dir("render-stale-foreign-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-stale-foreign\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"foreign.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");
    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    {
        let mut registry = Registry::open(&registry_path).expect("registry");
        registry
            .record_output_file(&OutputFileRecord {
                output_name: String::from("traefik"),
                scope: OutputFileScope::new(
                    root.with_file_name("deleted-worktree")
                        .join(".bindport/generated"),
                    root.with_file_name("deleted-worktree"),
                    None,
                    None,
                ),
                route_key: String::from("stale-foreign-route"),
                rendered_path: root
                    .with_file_name("deleted-worktree")
                    .join(".bindport/generated/traefik/stale.yml"),
                status: OutputFileStatus::Rendered,
                reason: None,
                content_hash: Some(String::from("deadbeef")),
                template_hash: None,
                lease_id: None,
                run_id: None,
            })
            .expect("record stale foreign output");
    }

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");
    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");

    assert_eq!(status["outputs"][0]["rendered"], 2);
    assert_eq!(status["outputs"][0]["removed"], 0);
}

#[test]
fn render_repair_adopts_content_matching_unowned_files() {
    let registry_path = temp_registry_path("render-repair-adopt-registry");
    let root = temp_test_dir("render-repair-adopt-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-repair-adopt\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"adopt.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");
    let rendered_path = root.join(".bindport/generated/traefik/web.yml");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");
    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");
    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    let rendered_contents = fs::read_to_string(&rendered_path).expect("rendered file");

    let route_key = {
        let status_output = bindport_with_registry(&registry_path)
            .args(["status", "--json"])
            .output()
            .expect("status json");
        let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");
        status["services"][0]["identity_key"]
            .as_str()
            .expect("identity key")
            .to_owned()
    };
    {
        let mut registry = Registry::open(&registry_path).expect("registry");
        registry
            .record_output_file(&OutputFileRecord {
                output_name: String::from("traefik"),
                scope: output_scope_for_root(&root),
                route_key,
                rendered_path: rendered_path.clone(),
                status: OutputFileStatus::Removed,
                reason: Some(String::from("lost_ownership_fixture")),
                content_hash: None,
                template_hash: None,
                lease_id: None,
                run_id: None,
            })
            .expect("remove output ownership");
    }
    assert_eq!(
        fs::read_to_string(&rendered_path).expect("rendered file remains"),
        rendered_contents
    );

    let rerender = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("rerender output");
    assert!(
        !rerender.status.success(),
        "normal render should still refuse unowned files"
    );
    assert!(
        String::from_utf8_lossy(&rerender.stderr).contains("unowned output file"),
        "unexpected stderr: {}",
        String::from_utf8_lossy(&rerender.stderr)
    );

    let repair = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "--repair", "traefik"])
        .output()
        .expect("repair output");
    assert!(
        repair.status.success(),
        "repair failed: {}",
        String::from_utf8_lossy(&repair.stderr)
    );
    let repair_stdout = String::from_utf8(repair.stdout).expect("repair stdout");
    assert!(repair_stdout.contains("repaired traefik: 0 files"));
    assert!(repair_stdout.contains("adopted traefik: 1 files"));

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");

    assert_eq!(status["outputs"][0]["rendered"], 1);
    assert_eq!(status["services"][0]["outputs"][0]["status"], "rendered");
}

#[test]
fn render_repair_refuses_to_adopt_content_divergent_unowned_files() {
    let registry_path = temp_registry_path("render-repair-divergent-registry");
    let root = temp_test_dir("render-repair-divergent-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-repair-divergent\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"divergent.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");
    let rendered_path = root.join(".bindport/generated/traefik/web.yml");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");
    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");
    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    let rendered_contents = fs::read_to_string(&rendered_path).expect("rendered file");

    let route_key = {
        let status_output = bindport_with_registry(&registry_path)
            .args(["status", "--json"])
            .output()
            .expect("status json");
        let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");
        status["services"][0]["identity_key"]
            .as_str()
            .expect("identity key")
            .to_owned()
    };
    {
        let mut registry = Registry::open(&registry_path).expect("registry");
        registry
            .record_output_file(&OutputFileRecord {
                output_name: String::from("traefik"),
                scope: output_scope_for_root(&root),
                route_key,
                rendered_path: rendered_path.clone(),
                status: OutputFileStatus::Removed,
                reason: Some(String::from("lost_ownership_fixture")),
                content_hash: None,
                template_hash: None,
                lease_id: None,
                run_id: None,
            })
            .expect("remove output ownership");
    }

    let divergent_contents = format!("{rendered_contents}\nmanual edit\n");
    fs::write(&rendered_path, &divergent_contents).expect("modify unowned file");

    let repair = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "--repair", "traefik"])
        .output()
        .expect("repair output");
    assert!(
        !repair.status.success(),
        "repair should refuse divergent unowned files"
    );
    assert!(
        String::from_utf8_lossy(&repair.stderr).contains("unowned output file"),
        "unexpected stderr: {}",
        String::from_utf8_lossy(&repair.stderr)
    );
    assert_eq!(
        fs::read_to_string(&rendered_path).expect("divergent file remains"),
        divergent_contents
    );
}
