// SPDX-License-Identifier: MIT

use crate::support::*;

#[test]
fn templates_export_builtin_traefik_template() {
    let registry_path = temp_registry_path("templates-builtin-registry");
    let output = bindport_with_registry(&registry_path)
        .args(["templates", "export", "bindport-traefik"])
        .output()
        .expect("export built-in template");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout");

    assert!(stdout.contains("Generated by BindPort"));
    assert!(stdout.contains(r#"("Host(`" ~ route.hostname ~ "`)") | tojson"#));
}

#[test]
fn templates_export_builtin_caddy_template() {
    let registry_path = temp_registry_path("templates-builtin-caddy-registry");
    let output = bindport_with_registry(&registry_path)
        .args(["templates", "export", "bindport-caddy"])
        .output()
        .expect("export built-in template");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout");

    assert!(stdout.contains("Generated by BindPort"));
    assert!(stdout.contains("reverse_proxy {{ route.target_url | tojson }}"));
}

#[test]
fn templates_export_builtin_json_snapshot_template() {
    let registry_path = temp_registry_path("templates-builtin-json-registry");
    let output = bindport_with_registry(&registry_path)
        .args(["templates", "export", "bindport-json-snapshot"])
        .output()
        .expect("export built-in template");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout");

    assert!(stdout.contains("\"snapshot\": {{ snapshot | tojson }}"));
    assert!(stdout.contains("\"routes\": {{ routes | tojson }}"));
}

#[test]
fn project_template_shadows_builtin_template() {
    let registry_path = temp_registry_path("templates-project-registry");
    let root = temp_test_dir("templates-project-root");
    let template_dir = root.join(".bindport").join("templates");
    fs::create_dir_all(&template_dir).expect("template dir");
    fs::write(
        root.join(".bindport.toml"),
        "project = \"template-project\"\n",
    )
    .expect("project config");
    fs::write(
        template_dir.join("bindport-traefik.yaml.j2"),
        "project template\n",
    )
    .expect("project template");

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["templates", "export", "bindport-traefik"])
        .output()
        .expect("export project template");

    assert!(output.status.success());
    assert_eq!(output.stdout, b"project template\n");
}
#[test]
fn templates_source_option_bypasses_project_shadow() {
    let registry_path = temp_registry_path("templates-source-registry");
    let root = temp_test_dir("templates-source-root");
    let template_dir = root.join(".bindport").join("templates");
    fs::create_dir_all(&template_dir).expect("template dir");
    fs::write(
        root.join(".bindport.toml"),
        "project = \"template-project\"\n",
    )
    .expect("project config");
    fs::write(template_dir.join("bindport-traefik"), "project template\n")
        .expect("project template");

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args([
            "templates",
            "show",
            "--source",
            "built-in",
            "bindport-traefik",
        ])
        .output()
        .expect("show built-in template");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout");

    assert!(stdout.contains("source: built-in"));
    assert!(stdout.contains("Generated by BindPort"));
    assert!(!stdout.contains("project template"));
}
