// SPDX-License-Identifier: MIT

mod support;

use support::*;

#[test]
fn templates_export_builtin_traefik_template() {
    let registry_path = temp_registry_path("templates-builtin-registry");
    let output = bindport_with_registry(&registry_path)
        .args(["templates", "export", "bindport-traefik"])
        .output()
        .expect("export built-in template");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout");

    assert!(stdout.contains("Generated by BindPort"));
    assert!(stdout.contains(r#"("Host(`" ~ route.hostname ~ "`)") | tojson"#));
}
#[test]
fn project_template_shadows_builtin_template() {
    let registry_path = temp_registry_path("templates-project-registry");
    let root = temp_test_dir("templates-project-root");
    let template_dir = root.join(".bindport").join("templates");
    fs::create_dir_all(&template_dir).expect("template dir");
    fs::write(
        root.join(".bindport.toml"),
        "project = \"template-project\"\n",
    )
    .expect("project config");
    fs::write(
        template_dir.join("bindport-traefik.yaml.j2"),
        "project template\n",
    )
    .expect("project template");

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["templates", "export", "bindport-traefik"])
        .output()
        .expect("export project template");

    assert!(output.status.success());
    assert_eq!(output.stdout, b"project template\n");
}
#[test]
fn templates_source_option_bypasses_project_shadow() {
    let registry_path = temp_registry_path("templates-source-registry");
    let root = temp_test_dir("templates-source-root");
    let template_dir = root.join(".bindport").join("templates");
    fs::create_dir_all(&template_dir).expect("template dir");
    fs::write(
        root.join(".bindport.toml"),
        "project = \"template-project\"\n",
    )
    .expect("project config");
    fs::write(template_dir.join("bindport-traefik"), "project template\n")
        .expect("project template");

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args([
            "templates",
            "show",
            "--source",
            "built-in",
            "bindport-traefik",
        ])
        .output()
        .expect("show built-in template");

    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).expect("stdout");

    assert!(stdout.contains("source: built-in"));
    assert!(stdout.contains("Generated by BindPort"));
    assert!(!stdout.contains("project template"));
}
#[test]
fn render_command_writes_config_files_and_records_ownership() {
    let registry_path = temp_registry_path("render-output-registry");
    let root = temp_test_dir("render-output-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-project\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"render.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let rendered_path = root
        .join(".bindport")
        .join("generated")
        .join("traefik")
        .join("web.yml");
    let dry_run = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik", "--dry-run"])
        .output()
        .expect("dry-run render");

    assert!(
        dry_run.status.success(),
        "render dry-run failed: {}",
        String::from_utf8_lossy(&dry_run.stderr)
    );
    let dry_run_stdout = String::from_utf8(dry_run.stdout).expect("dry-run stdout");
    assert!(dry_run_stdout.contains("would render traefik: 1 files"));
    assert!(dry_run_stdout.contains("traefik/web.yml"));
    assert!(!rendered_path.exists());

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");

    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    assert!(
        String::from_utf8(render.stdout)
            .expect("render stdout")
            .contains("rendered traefik: 1 files")
    );

    let contents = fs::read_to_string(&rendered_path).expect("rendered file");
    assert!(contents.contains("Generated by BindPort"));
    assert!(contents.contains("is stopped"));

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    assert!(
        status_output.status.success(),
        "status failed: {}",
        String::from_utf8_lossy(&status_output.stderr)
    );
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");
    let rendered_path_string = rendered_path
        .canonicalize()
        .expect("canonical rendered path")
        .display()
        .to_string();

    assert_eq!(status["schema_version"], "0.4");
    assert_eq!(status["outputs"][0]["name"], "traefik");
    assert_eq!(status["outputs"][0]["pending"], 0);
    assert_eq!(status["outputs"][0]["rendered"], 1);
    assert_eq!(status["outputs"][0]["removed"], 0);
    assert_eq!(status["outputs"][0]["error"], 0);
    assert_eq!(status["services"][0]["outputs"][0]["name"], "traefik");
    assert_eq!(status["services"][0]["outputs"][0]["status"], "rendered");
    assert_eq!(
        status["services"][0]["outputs"][0]["path"],
        rendered_path_string
    );
    assert_eq!(status["services"][0]["proxy"]["adapter"], "traefik");
    assert_eq!(status["services"][0]["proxy"]["rendered"], true);
    assert_eq!(
        status["services"][0]["proxy"]["target"],
        rendered_path_string
    );

    let rerender = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("rerender output");

    assert!(
        rerender.status.success(),
        "rerender failed: {}",
        String::from_utf8_lossy(&rerender.stderr)
    );
}
#[test]
fn render_all_writes_every_enabled_output() {
    let registry_path = temp_registry_path("render-all-registry");
    let root = temp_test_dir("render-all-root");
    let template_dir = root.join(".bindport").join("templates");
    fs::create_dir_all(&template_dir).expect("template dir");
    fs::write(
        template_dir.join("debug-route.txt.j2"),
        "debug {{ output.name }} {{ route.service }} {{ vars.mode }} {{ route.target_url }}\n",
    )
    .expect("write debug template");

    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-all\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"render-all.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n[[outputs]]\nname = \"debug\"\ntemplate = \"debug-route\"\nroot = \".bindport/generated\"\ntarget = \"debug/{{{{ route.service }}}}.txt\"\nauto_render = false\n[outputs.vars]\nmode = \"dev\"\n"
        ),
    )
    .expect("write render config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "--all"])
        .output()
        .expect("render all outputs");

    assert!(
        render.status.success(),
        "render all failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    let stdout = String::from_utf8(render.stdout).expect("render stdout");
    assert!(stdout.contains("rendered traefik: 1 files"));
    assert!(stdout.contains("rendered debug: 1 files"));

    assert!(root.join(".bindport/generated/traefik/web.yml").is_file());
    assert_eq!(
        fs::read_to_string(root.join(".bindport/generated/debug/web.txt"))
            .expect("debug rendered file"),
        format!("debug debug web dev http://127.0.0.1:{port}")
    );
}
#[test]
fn render_env_local_output_writes_opt_in_dotenv_file() {
    let registry_path = temp_registry_path("render-env-local-registry");
    let root = temp_test_dir("render-env-local-root");
    fs::write(
        root.join(".bindport.toml"),
        "project = \"env-local-project\"\ndefault_range = \"29430-29439\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"env-local.localhost\"\n[[outputs]]\nname = \"env-local\"\ntemplate = \"bindport-env-local\"\ntarget = \"apps/{{ route.service }}/.env.local\"\nauto_render = false\n",
    )
    .expect("write env-local config");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "env-local"])
        .output()
        .expect("render env-local output");

    assert!(
        render.status.success(),
        "render env-local failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    let stdout = String::from_utf8(render.stdout).expect("render stdout");
    assert!(stdout.contains("rendered env-local: 1 files"));

    let env_file = root.join("apps/web/.env.local");
    let contents = fs::read_to_string(&env_file).expect("env-local file");
    let rendered_port = dotenv_value(&contents, "PORT")
        .expect("rendered port")
        .parse::<u16>()
        .expect("rendered port is numeric");
    assert!((29430..=29439).contains(&rendered_port));
    assert!(contents.contains(r#"BINDPORT_PROJECT="env-local-project""#));
    assert!(contents.contains(r#"BINDPORT_SERVICE="web""#));
    assert!(contents.contains(r#"BINDPORT_STATE="stopped""#));
    assert!(contents.contains(&format!(
        r#"BINDPORT_TARGET_URL="http://127.0.0.1:{rendered_port}""#
    )));
    assert!(contents.contains(r#"BINDPORT_HOSTNAME="env-local.localhost""#));
    assert!(contents.contains(r#"BINDPORT_ROUTE_URL="http://env-local.localhost""#));
}
#[test]
fn render_repair_records_externally_modified_owned_files() {
    let registry_path = temp_registry_path("render-repair-modified-registry");
    let root = temp_test_dir("render-repair-modified-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-repair\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"repair.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");
    let rendered_path = root.join(".bindport/generated/traefik/web.yml");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");
    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );

    let render = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "traefik"])
        .output()
        .expect("render output");
    assert!(
        render.status.success(),
        "render failed: {}",
        String::from_utf8_lossy(&render.stderr)
    );
    fs::write(&rendered_path, "external change").expect("modify rendered file");

    let repair = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["render", "--repair", "traefik"])
        .output()
        .expect("repair output");
    assert!(
        repair.status.success(),
        "repair failed: {}",
        String::from_utf8_lossy(&repair.stderr)
    );
    let repair_stdout = String::from_utf8(repair.stdout).expect("repair stdout");
    assert!(repair_stdout.contains("repaired traefik: 0 files"));
    assert!(repair_stdout.contains("preserved traefik: 1 externally modified files"));
    assert_eq!(
        fs::read_to_string(&rendered_path).expect("preserved file"),
        "external change"
    );

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");

    assert_eq!(status["outputs"][0]["rendered"], 0);
    assert_eq!(status["outputs"][0]["error"], 1);
    assert_eq!(status["services"][0]["outputs"][0]["status"], "error");
    assert_eq!(
        status["services"][0]["outputs"][0]["reason"],
        "external_modified"
    );
}
#[test]
fn runner_blocks_start_when_required_output_preflight_fails() {
    let registry_path = temp_registry_path("render-block-preflight-registry");
    let root = temp_test_dir("render-block-preflight-root");
    let port = free_loopback_port();
    let marker_path = root.join("child-ran");
    let marker_arg = marker_path.display().to_string();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"render-block\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"block.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"../blocked.yml\"\non_failure = \"block\"\n"
        ),
    )
    .expect("write render config");

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args([
            "run",
            "web",
            "--",
            "sh",
            "-c",
            "printf ran > \"$1\"",
            "sh",
            &marker_arg,
        ])
        .output()
        .expect("run bindport");

    assert!(!output.status.success());
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("unsafe output target"),
        "unexpected stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(!marker_path.exists());
}
#[test]
fn runner_auto_renders_outputs_on_start_and_exit() {
    let registry_path = temp_registry_path("auto-render-registry");
    let root = temp_test_dir("auto-render-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"auto-render-project\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"auto.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\n"
        ),
    )
    .expect("write render config");

    let rendered_path = root
        .join(".bindport")
        .join("generated")
        .join("traefik")
        .join("web.yml");
    let mut bindport = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "sleep 2"])
        .spawn()
        .expect("spawn bindport");

    let active_contents =
        wait_for_file_contains(&rendered_path, "routers:", Duration::from_secs(5));
    assert!(active_contents.contains("Host(`auto.localhost`)"));
    assert!(active_contents.contains(&format!("url: \"http://127.0.0.1:{port}\"")));

    let status = wait_for_child(&mut bindport, Duration::from_secs(5)).expect("bindport exits");
    assert!(status.success());

    let stopped_contents =
        wait_for_file_contains(&rendered_path, "is stopped", Duration::from_secs(5));
    assert!(!stopped_contents.contains("routers:"));
}
#[test]
fn runner_skips_outputs_when_auto_render_is_disabled() {
    let registry_path = temp_registry_path("auto-render-disabled-registry");
    let root = temp_test_dir("auto-render-disabled-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"auto-render-disabled\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"disabled.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\nauto_render = false\n"
        ),
    )
    .expect("write render config");

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(!root.join(".bindport/generated/traefik/web.yml").exists());
}
#[test]
#[cfg(unix)]
fn runner_auto_renders_stale_routes_reconciled_during_route_event() {
    let registry_path = temp_registry_path("auto-render-stale-registry");
    let root = temp_test_dir("auto-render-stale-root");
    let stale_port = free_loopback_port();
    let active_port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"auto-render-stale\"\ndefault_range = \"{active_port}-{active_port}\"\nskip_ports = []\n[[services]]\nname = \"api\"\nhostname = \"api.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\n"
        ),
    )
    .expect("write render config");

    let mut registry = Registry::open(&registry_path).expect("registry");
    let identity = ServiceIdentity {
        project: String::from("auto-render-stale"),
        service: String::from("web"),
        git: None,
        identity_key: String::from("v1:auto-render-stale:web"),
    };
    registry
        .record_run_started(&RunStart {
            project: identity.project.clone(),
            service: identity.service.clone(),
            identity: Some(identity),
            host: String::from("127.0.0.1"),
            port: stale_port,
            hostname: Some(String::from("web.localhost")),
            route_url: Some(String::from("http://web.localhost")),
            health_url: None,
            pid: 2_000_000_000,
            command: String::from("stale fixture"),
            cwd: root.clone(),
        })
        .expect("record stale fixture");
    drop(registry);

    let output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "api", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let stale_contents = fs::read_to_string(root.join(".bindport/generated/traefik/web.yml"))
        .expect("stale route render");
    assert!(stale_contents.contains(" is stale, so no live router was rendered."));
    assert!(!stale_contents.contains("routers:"));

    let status_output = bindport_with_registry(&registry_path)
        .args(["status", "--json"])
        .output()
        .expect("status json");
    assert!(status_output.status.success());
    let status = serde_json::from_slice::<Value>(&status_output.stdout).expect("status json");
    let services = status["services"].as_array().expect("services");
    let stale_service = services
        .iter()
        .find(|service| service["service"] == "web")
        .expect("stale service");

    assert_eq!(stale_service["state"], "stale");
    assert_eq!(stale_service["outputs"][0]["status"], "rendered");
}
#[test]
fn runner_delete_on_stopped_removes_owned_output_file_after_exit() {
    let registry_path = temp_registry_path("delete-on-stopped-registry");
    let root = temp_test_dir("delete-on-stopped-root");
    let port = free_loopback_port();
    fs::write(
        root.join(".bindport.toml"),
        format!(
            "project = \"delete-on-stopped\"\ndefault_range = \"{port}-{port}\"\nskip_ports = []\n[[services]]\nname = \"web\"\nhostname = \"stopped.localhost\"\n[[outputs]]\nname = \"traefik\"\ntemplate = \"bindport-traefik\"\nroot = \".bindport/generated\"\ntarget = \"traefik/{{{{ route.service }}}}.yml\"\ndelete_on = [\"stopped\", \"removed\"]\n"
        ),
    )
    .expect("write output config");
    let rendered_path = root.join(".bindport/generated/traefik/web.yml");

    let run_output = bindport_with_registry(&registry_path)
        .current_dir(&root)
        .args(["run", "web", "--", "sh", "-c", "true"])
        .output()
        .expect("run bindport");

    assert!(
        run_output.status.success(),
        "bindport failed: {}",
        String::from_utf8_lossy(&run_output.stderr)
    );
    assert!(!rendered_path.exists());
}
